version: '3.8'

services:

  eureka:
    build:
      context: ./registration
    ports:
      - "8761:8761"
    container_name: eureka
    networks:
      - app-network

  encryption:
    build:
      context: ./encryption
    ports:
      - "8081:8081"
    container_name: encryption
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - app-network

  decryption:
    build:
      context: ./decryption
    ports:
      - "8082:8082"
    container_name: decryption
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - app-network

  gateway:
    build:
      context: ./gateway
    ports:
      - "8080:8080"
    container_name: gateway
    depends_on:
      - eureka
      - encryption
      - decryption
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - app-network

  webserver:
    build:
      context: ./webserver
    ports:
      - "8083:8083"
    container_name: webserver
    depends_on:
      - gateway
    environment:
      - GATEWAY_URL=http://gateway:8080
    networks:
      - app-network

networks:
  app-network:
