apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration
  template:
    metadata:
      labels:
        app: registration
    spec:
      containers:
        - name: registration
          image: europe-docker.pkg.dev/amazing-smile-460208-a6/registration-repo/registration:latest
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: registration
spec:
  selector:
    app: registration
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer
