server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: encryption-service
          uri: lb://encryption-service
          predicates:
            - Path=/encrypt/**

        - id: decryption-service
          uri: lb://decryption-service
          predicates:
            - Path=/decrypt/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
