server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: encryption-service
          uri: http://localhost:8081
          predicates:
            - Path=/encrypt

        - id: decryption-service
          uri: http://localhost:8082
          predicates:
            - Path=/decrypt
            
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
